version: "3"

services:
  app:
    build: .
    deploy:
      replicas: 3
    # ports:
    #   - "8080-8082:8080"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  pushpin:
    image: fanout/pushpin
    ports:
      - "7999:7999"
    volumes:
      - ./pushpin-routes:/etc/pushpin/routes
