version: '3'

services:
  app:
    image: go_chat
    deploy:
      replicas: 3
    ports:
      - "8080-8082:8080"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
